name: Build and deploy Python project to Azure Function App - NumberRecognition

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZUREWEBJOBSSTORAGE: "DefaultEndpointsProtocol=https;AccountName=stockagenbrecognition1;AccountKey=sVqYPM0Wv6FhCP975LsNRtXNQz2Qxtr8kBg8W4tasPJZ6VHXWzxPcH2sr+SiqU7SFlOezCe8QGMt+ASt4AINEw==;EndpointSuffix=core.windows.net"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source env/bin/activate
          pytest --junitxml=test-results.xml

      - name: Train model
        run: |
          source env/bin/activate
          python test/test_model.py

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

      - name: Zip artifact for deployment
        run: |
          source env/bin/activate
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set AzureWebJobsStorage
        run: |
          az functionapp config appsettings set --name NumberRecognition --resource-group NumberRecognition --settings AzureWebJobsStorage=${{ secrets.AZUREWEBJOBSSTORAGE }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'NumberRecognition'
          slot-name: 'Production'
          package: '../../.'
          scm-do-build-during-deployment: true
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          enable-oryx-build: true
